### ISSUE TITLE
Open-Source Collaboration on Appfairy

### ISSUE THREAD

**Issue by oagix** [franciscofsales/react-native-animated-list#3]
Hey @franciscofsales ,

I'm writing an issue here because I couldn't otherwise get in touch with you through your GitHub. My name is Alex and I recently forked a branch from a repository called "Appfairy" that you contributed to earlier this year.

I started re-shaping it in an attempt to create an easier way to convert Webflow projects to React JS for a personal project I'm working on. I noticed your version is working a lot better than the original, as well as that there have been a lot of good patches pushed through.

Since the repository looked dead and my vision over it was to turn it into a Webflow to React JS solution, I continued development here: https://github.com/Abruptive/webflow-react

Would you be interested in helping me get the script to work properly since you already have a deep understanding over it? 

Cheers!
Alex

**Comment by franciscofsales** [comment]
Hi Alex,

I am sending an email with my contacts so we can collaborate better.

Cheers
